export const literals = {
  genericError: "Κάτι πήγε στραβά! Δοκιμάστε ξανά!",
  invalidCredentials:
    "Μη έγκυρα διαπιστευτήρια. Παρακαλώ ελέγξτε το email και τον κωδικό πρόσβασής σας και δοκιμάστε ξανά.",
  createTableButtonText: "Δημιουργία Τραπεζίου",
  createWaiterButtonText: "Δημιουργία Χρήστη",
  createProductsButtonText: "Δημιουργία Προϊόντος",
  createText: "Δημιουργία",
  updateText: "Ενημέρωση",
  notFoundText: "Δεν βρέθηκαν εγγραφές!",
  successText: "Η διαδικασία ολοκληρώθηκε με επιτυχία!",
  userText: "Γειά σου %!",
  toBeMadeText: "Πρως υλοποίση",
  toBePaidText: "Πρως πληρωμή",
  paidText: "Πληρωμένη",
  tableText: "Τραπέζι",
  details: "Λεπτομέρειες",
  waitressText: "Σερβιτόρος",
  codeText: "Κωδικός",
  completedText: "Ολοκληρωμένη",
  costText: "Κόστος",
  totalText: "Σύνολο",
  waiterPinText: "Ο Κωδικός πιστοποίησης σερβιτόρου ειναι %",
  waiterForgotPasswordText: "Επαναφορά κωδικού πρόσβασης",
};
